import ReactDOM from "react-dom/client";
// import App from "./App_class";
// import App from "./01_类组件和函数式组件/App_func";
// import App from "./02_组件生命周期函数/App";
// import App from "./03_组件开发嵌套关系/App";
// import App from "./04_组件通信-父传子/App";
// import App from "./05_组件通信-子传父/App";
// import App from "./06_组件通信案例练习/App";
// import App from "./07_组件的插槽实现/App";
// import App from "./08_组件作用域插槽/App";
// import App from "./09_非父子通信-Context/App";
// import App from "./11_setState的详细使用/App";
// import App from "./12_render函数的优化/App";
// import App from "./13_数据不可变的力量/App";
// import App from "./14_ref获取DOM和组件/App";
// import App from "./15_受控和非受控组件/App";
// import App from "./16_React高阶组件/App";
// import App from "./17_React的Portals/App";
// import App from "./18_React的Fragment/App";
// import App from "./19_React的严格模式/App";
import App from "./20_React的动画实现/App";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
